name: garantias
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:  # ✅ Ahora está bien ubicado
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  provider: ^6.1.5
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  mailer: ^6.4.1
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
